
on: push  
name: Reproducibility

jobs:
  render:
    name: Render Assignment
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1 
      - name: Install Package Dependencies
        shell: Rscript {0}
        run: |-
          install.packages("remotes")
          remotes::install_local(".")
      - name: Render
        shell: Rscript {0}
        run: |-
          lapply(fs::dir_ls('assignment', glob='*.Rmd', recurse=TRUE), rmarkdown::render, envir = globalenv())
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit assignment -m 'Re-build Rmd' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
          
